# Generated by Django 4.2.5 on 2023-10-31 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atletas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('faixa_categoria', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('local', models.CharField(max_length=100)),
                ('valor_inscricao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('atleta1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights_atleta1', to='atletas.atleta')),
                ('atleta2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights_atleta2', to='atletas.atleta')),
            ],
        ),
    ]
