# Generated by Django 4.2.6 on 2023-10-11 18:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_noticia_conteudo_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='conteudo_noticia',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
