# Generated by Django 4.2.5 on 2023-10-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='faixa',
            field=models.CharField(choices=[('Branca', 'Branca'), ('Amarela', 'Amarela'), ('Amarela', 'Amarela-Verde'), ('Verde', 'Verde'), ('Verde', 'Verde-Azul'), ('Azul', 'Azul'), ('Azul', 'Azul-Vermelha'), ('Vermelha', 'Vermelha'), ('Vermelha', 'Vermelha-Preta'), ('Preta', 'Preta 1 ao 9 DAN')], max_length=10),
        ),
    ]
